**PROGRAMOWANIE ZAAWANSOWANE LAB 04**

Autor: Zuzanna Soboń  
Nr albumu: 191671  
Link do gita: https://github.com/sobonzuzanna/programowanie-semestr4/tree/main/lab04

In [40]:
import numpy as np
import pandas as pd
from pymcdm.methods import TOPSIS, SPOTIS
from pymcdm.normalizations import minmax_normalization
from pymcdm.weights import entropy_weights

# 4 smartfony
# Kryteria: Cena (min), RAM (max), Bateria (max), Aparat (max)

# 4.2.1
macierz_decyzyjna = np.array([
    [1000, 5000, 12, 0.2],  # iPhone 15
    [1500, 6000, 10, 0.3],  # Galaxy S23
    [2000, 7000, 8, 0.1],   # Motorola
    [1200, 5500, 9, 0.15]   # Xiaomi
])

print("Macierz decyzyjna:")
print(macierz_decyzyjna)

# 4.2.2 wyznaczenie wag metodą Entropii 
wagi = entropy_weights(macierz_decyzyjna)

print("\nWyznaczone wagi (entropią):")
print(wagi)

# 4.2.3
typy_kryteriow = np.array([-1, 1, 1, 1])  # Koszty, zyski, czas, ryzyko

# 4.3.2 normalizacja danych
znormalizowana = np.array([minmax_normalization(macierz_decyzyjna[:, i], typy_kryteriow[i] == -1) for i in range(macierz_decyzyjna.shape[1])]).T

# 4.3.3 uruchomienie metod MCDM

topsis = TOPSIS()

granice = np.vstack((
    np.min(znormalizowana, axis=0), 
    np.max(znormalizowana, axis=0)
)).T

spotis = SPOTIS(granice)

wynik_topsis = topsis(znormalizowana, wagi, typy_kryteriow)
wynik_spotis = spotis(znormalizowana, wagi, typy_kryteriow)


# 4.3.4 wyniki
wyniki = pd.DataFrame({
    'Smartfon': ['iPhone 15', 'Galaxy S23', 'Motorola', 'Xiaomi'],
    'Ocena TOPSIS': wynik_topsis,
    'Ocena SPOTIS': wynik_spotis,
})

print("\nWyniki:")
print(wyniki.to_string())


Macierz decyzyjna:
[[1.0e+03 5.0e+03 1.2e+01 2.0e-01]
 [1.5e+03 6.0e+03 1.0e+01 3.0e-01]
 [2.0e+03 7.0e+03 8.0e+00 1.0e-01]
 [1.2e+03 5.5e+03 9.0e+00 1.5e-01]]

Wyznaczone wagi (entropią):
[0.26240998 0.06009483 0.08712826 0.59036693]

Wyniki:
     Smartfon  Ocena TOPSIS  Ocena SPOTIS
0   iPhone 15      0.435152      0.617688
1  Galaxy S23      0.811002      0.204817
2    Motorola      0.310871      0.677495
3      Xiaomi      0.242440      0.763120
